firstsite/firstsite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('wishlist/', include('wishlist.urls'))
]

firstsite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('login/', views.LoginPageView.as_view(), name='login_page'),
    path('register/', views.RegisterPageView.as_view(), name='register_page'),
    path('auth/login', views.logins, name='login'),
    path('auth/register', views.register, name='register'),
    path('auth/logout', views.logouts, name='logout')
]

firstsite/wishlist/urls.py
from django.urls import path, include

from wishlist.views import IndexView, RegisterView, RegisterView, CreateListView, ReadWishListView, WishListListView, WishListEditView

app_name = 'wishlist'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register', RegisterView.as_view(), name='register'),
    path('wishlist/create', CreateListView.as_view(), name='wishlist_create'),
    path('wishlist/<int:pk>', ReadWishListView.as_view(), name='wishlist_read'),
    path('wishlist/', WishListListView.as_view(), name='wishlist_list'),
    path('wishlist/<int:pk>/edit', WishListEditView.as_view(), name='wishlist_edit')
]

firstsite/wishlist/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class WishList(models.Model):
    name = models.CharField(max_length=200)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    created_date = models.DateTimeField('date of creation')

class Wish(models.Model):
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    description = models.CharField(max_length=200,blank=True)
    wishlist = models.ForeignKey(WishList, on_delete=models.CASCADE)

firstsite/wishlist/forms.py
from django import forms
from wishlist.models import WishList, Wish


class WishListForm(forms.ModelForm):
    """
    Form that let you manipulate a WishList model
    """
    class Meta:
        model = WishList
        fields = ['name']

class WishForm(forms.ModelForm):
    class Meta:
        model = Wish
        fields = ['name', 'price', 'description']

firstsite/wishlist/views.py
from django.shortcuts import render
from django import views
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from django.urls import reverse
from django.forms import formset_factory
from django.db import transaction, IntegrityError
from wishlist.messages import ErrorMessage

from wishlist.models import WishList, Wish
from wishlist.forms import WishListForm, WishForm

import logging
logger = logging.getLogger(__name__)

# Create your views here.
class IndexView(views.generic.base.TemplateView): #pylint: disable=C0111
    template_name = 'wishlist/index.html'

class RegisterView(views.View):
    def post(self, request):
        # Retrieve the form with POST data
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            # Create a user
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('index')
        else:
            messages.error(request, ErrorMessage.INVALID_FORM)
            form = UserCreationForm()
        return render(request, 'registration/register.html', {'form': form}) 

    def get(self, request):
        form = UserCreationForm()
        return render(request, 'registration/register.html', {'form': form})

class CreateListView(views.generic.CreateView):
    model = WishList
    def get(self, request):
        # Create a empty Wish list creation form
        form = WishListForm()
        return render(request, 'wishlist/wishlist_create.html', {'form': form})

    def post(self, request):
        # Retrieve the form filled with POST data
        form = WishListForm(request.POST)
        # If there is a logged user
        if request.user.is_authenticated:
            # And the form is valid
            if form.is_valid():
                # Create a Wishlist
                name = form.cleaned_data.get('name')
                wishlist = WishList(name=name, created_date=timezone.now(), owner=request.user)
                logger.info("Saving a wishlist to db.")
                # Save it in DB
                wishlist.save()
                # Redirect to consulting view
                return redirect(reverse('wishlist:wishlist_read', kwargs={'pk': wishlist.id}))
            else:
                messages.error(request, ErrorMessage.INVALID_FORM)
                return render(request, 'wishlist/wishlist_create.html', {'form': form})   
        else:
            messages.error(request, ErrorMessage.LOGGIN_REQUIRED)
            return render(request, 'registration/login.html')

class ReadWishListView(views.generic.DetailView):
    model = WishList
    template_name = 'wishlist/wishlist_read.html'

class WishListListView(views.generic.ListView):
    template_name = 'wishlist/wishlist_list.html'
    context_object_name = 'wishlists'
    # Returns wishlist created by the current user and user data
    def get_queryset(self):
        return {
            'wishlists': WishList.objects.filter(
                owner=self.request.user
            )
        }

class WishListEditView(views.View):
    def get(self, request, pk):
        # Get the Wishlist
        wishlist = WishList.objects.get(pk=pk)
        # Load wishlist data in form
        wishlist_form = WishListForm(instance=wishlist)
        # Get wish that are in the wishlist
        wishs = Wish.objects.filter(wishlist=wishlist).values()
        # Create a form for each wish and an extra one too add a wish.
        WishFormSet = formset_factory(WishForm, extra=1)
        # Load wish data in the form set
        wish_formset = WishFormSet(initial=wishs)
        # Render all.
        return render(request, 'wishlist/wishlist_edit.html', {'wishlist_form': wishlist_form, 'wish_formset': wish_formset, 'wishlist': wishlist})

    def post(self, request, pk):
        # Get the Wishlist
        wishlist = WishList.objects.get(pk=pk)
        # Retrieve the wishlist form with POST data
        wishlist_form = WishListForm(request.POST)
        # Instanciate a Wish form set
        WishFormSet = formset_factory(WishForm)
        # Retrieve the wish forms with POST data
        wish_formset = WishFormSet(request.POST)

        # If both wishlist form and wish forms are valid
        if wishlist_form.is_valid() and wish_formset.is_valid():

            # Update the wishlist data
            wishlist.name = wishlist_form.cleaned_data.get('name')
            wishlist.save()

            new_wish = []
            # Create a Wish object for each wish form
            for wish_form in wish_formset:
                name = wish_form.cleaned_data.get('name')
                price = wish_form.cleaned_data.get('price')
                description = "" if wish_form.cleaned_data.get('description') is None else wish_form.cleaned_data.get('description')
                
                if name and price and description:
                    new_wish.append(Wish(name=name, price=price, description=description))
                try:
                    with transaction.atomic():
                        # Replace olds wish with news
                        Wish.objects.filter(wishlist=wishlist).delete()
                        Wish.objects.bulk_create(new_wish)

                        # Add a notification
                        messages.success(request, "Wishlist updated.")
                except IntegrityError as exception:
                    # In case of error
                    # Add a failure notification
                    messages.error(request, ErrorMessage.ERROR_UPDATING_CHANGE)
                    logger.error(exception)
                    return redirect(reverse('wishlist:wishlist_edit', args=[pk]))
        else:
            messages.error(request, ErrorMessage.INVALID_FORM)

        context = {
            'wishlist_form': wishlist_form,
            'wish_formset': wish_formset
        }

        return render(request, 'wishlist/wishlist_edit.html', context)
        

firstsite/wishlist/templates/wishlist/index.html
{% extends "wishlist/layout.html" %}

{% block content %}
    <div class="content">
        <div class="title">Features</div>
        <ul>
            <li>Create a wishlist</li>
            <li>Share it with people</li>
            <li>Read a wishlist</li>
            <li>Say to other that you plan on getting an item of the list (the owner will not see)</li>
        </ul>
    </div>
    <br>
    <div class="content">
        <div class="title">Dashboard</div>
        <div>
            {% if user.is_authenticated %}
                <p>Welcome {{user.username}}</p>
                <p>
                    <a href="{% url 'wishlist:wishlist_create' %}">Create a wishlist</a>
                </p>
                <p>
                    <a href="{% url 'wishlist:wishlist_list' %}">My wishlists</a>
                </p>
            {% else %}
                <p>Please <a href="{% url 'wishlist:login'%}">log in</a>.</p>
            {% endif %}
        </div>
    </div>
{% endblock content %}

firstsite/wishlist/templates/wishlist/layout.html
{% load static %}
<html>
    <head>
        <title>Wishlist</title>
        <link rel="stylesheet" type="text/css" href="{% static 'wishlist/style.css' %}">
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    </head>
    <body>
        <header>
            <div class="logo">
                <p class="logo-title">Wishlist</p>
            </div>
            <nav>
                <ul>
                    <li><a href="{% url 'wishlist:index' %}">Home</a></li>
                    {% if user.is_authenticated %}
                        <li><a href="#">{{ user.username }}</a> <a href="{% url 'wishlist:logout' %}">Disconnect</a></li>
                    {% else %}
                        <li><a href="{% url 'wishlist:login' %}">Log in</a> / <a href="{% url 'wishlist:register' %}">Register</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>

        {% if messages %}
            <ul class="messages">
            {% for message in messages %}
                <li {%if message.tags %} class="{{message.tags}}-message" {%endif %}>{{ message }}</li>
            {% endfor %}
            </ul>
        {% endif %}    

        <main>
            {% block content %}
            {% endblock %}
        </main>
        <footer>
            <div class="copyrigth">
                &copy; Maxime Chevallier-Pichon 2018
            </div>
            {% if user.username == "admin" %}
                <div class="admin">
                    <a href="{% url 'admin:index' %}">Administration</a>
                </div>
            {% endif %}
        </footer>
    </body>
</html>

firstsite/wishlist/templates/wishlist/wishlist_create.html
{% extends "wishlist/layout.html" %}

{% block content %}
    <div class="content">
        <div class="title">Create a wishlist</div>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Create">
        </form>
    </div>
{% endblock content %}

firstsite/wishlist/templates/wishlist/wishlist_edit.html
{% extends "wishlist/layout.html" %}

{% block content %}
    <div class="content">
        <div class="title">Edit wishlist: {{ wishlist.name }}</div>
        <form method="POST">
            {% csrf_token %}
            <fieldset>
                <legend>Wishlist</legend>
                {{ form.errors.as_ul }}
                {{ wishlist_form.as_p }}
            </fieldset>
            <fieldset>
                <legend>Wishs:</legend>
                <table>
                    <thead>
                        <th>Name</th>
                        <th>Price</th>
                        <th>Description</th>
                    </thead>
                    {{ wish_formset.management_form }}
                    {% for form in wish_formset %}
                        {{ form.errors.as_ul }}
                        <tr>
                            {% for field in form %}
                                <td>{{ field }}</td>
                            {% endfor %}
                        </tr>
                    {% endfor %}
                </table>
            </fieldset>
            <input type="submit" value="Update">
        </form>
    </div>
{% endblock content %}

firstsite/wishlist/templates/wishlist/wishlist_list.html
{% extends "wishlist/layout.html" %}

{% block content %}
    <div class="content">
        <div class="title">Wishlist of {{ user.username }}</div>
        <ul>
            {% if wishlists.wishlists|length > 0 %}
                {% for wishlist in wishlists.wishlists %}
                    <li><a href="{% url 'wishlist:wishlist_read' wishlist.id %}">{{ wishlist.name|title }}</a> (<a href="{% url 'wishlist:wishlist_edit' wishlist.id %}">edit</a>) (<a href="">delete</a>)</li>
                {% endfor %}
            {% else %}
                <p>No wishlist. <a href="{% url 'wishlist:wishlist_create' %}">Create one.</a></p>
            {% endif %}
        </ul>
    </div>
{% endblock content %}

firstsite/wishlist/templates/wishlist/wishlist_read.html
{% extends "wishlist/layout.html" %}

{% block content %}
    <div class="content">
        <a href="{% url 'wishlist:wishlist_list' %}">Return to wishlists</a>
        <div class="title">Wishlist: {{wishlist.name}}</div>
        <p class="created_date">created on {{ wishlist.created_date }} by {{ wishlist.owner.username }}</p>
    </div>
{% endblock content %}