firstsite/firstsite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('wishlist/', include('wishlist.urls'))
]

firstsite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('login/', views.LoginPageView.as_view(), name='login_page'),
    path('register/', views.RegisterPageView.as_view(), name='register_page'),
    path('auth/login', views.logins, name='login'),
    path('auth/register', views.register, name='register'),
    path('auth/logout', views.logouts, name='logout')
]

firstsite/polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'
        
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

firstsite/polls/views.py
import hashlib
import logging
logger = logging.getLogger(__name__)

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import timezone
from django.views import generic

from .models import Choice, Question

PASSWORD_SALT = "43518e2530f6db29d2c80a65600b620cd4acfddc1b53e214063fef9bd6f3207d"

class IndexView(generic.ListView): #pyling: disable=C0111
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView): #pyling: disable=C0111
    model = Question
    template_name = 'polls/detail.html'
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView): #pyling: disable=C0111
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id): #pyling: disable=C0111
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        messages.error(request, "You didn't select a choice.")
        return render(request, 'polls/detail.html', {
            'question': question
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

class LoginPageView(generic.base.TemplateView): #pyling: disable=C0111
    template_name = 'polls/login.html'

def logins(request): #pyling: disable=C0111
    username = request.POST['username']
    password = request.POST['password']
    if username is not "" and password is not "":
        password_hashed = hashlib.sha512((PASSWORD_SALT + password).encode('utf-8')).hexdigest()
        user = authenticate(request, username=username, password=password_hashed)
        if user is not None:
            login(request, user)
            messages.success(request, "Login successful !")
            return HttpResponseRedirect(reverse('polls:index'))
        else:
            messages.error(request, "Bad credentials")
            return render(request, 'polls/login.html')
    else:
        messages.error(request, "Username or password unset.")
        return render(request, 'polls/login.html')

class RegisterPageView(generic.base.TemplateView): #pyling: disable=C0111
    template_name = 'polls/register.html'

def register(request): #pyling: disable=C0111
    username = request.POST['username']
    password = request.POST['password']
    cpassword = request.POST['cpassword']
    if username is not "" and password is not "" and cpassword is not "":
        if password == cpassword:
            if User.objects.filter(username=username).exists() is False:
                if len(password) > 5:
                    password_hashed = hashlib.sha512((PASSWORD_SALT + password).encode('utf-8')).hexdigest()
                    User.objects.create_user(username=username, password=password_hashed)
                    messages.success(request, "Register successful.")
                    return HttpResponseRedirect(reverse('polls:login_page'))
                else:
                    messages.error(request, "Your password is too short (it shoulds be greater than 5 characters).")
                    return render(request, 'polls/register.html')
            else:
                messages.error(request, "Username already exists.")
                return render(request, 'polls/register.html')
        else:
            messages.error(request, "Passwords don't match.")
            return render(request, 'polls/register.html')
    else:
        messages.error(request, "Required fields unsets.")
        return render(request, 'polls/register.html')

def logouts(request):
    logout(request)
    messages.success(request, "Logged out.")
    return HttpResponseRedirect(reverse('polls:index'))

firstsite/polls/templates/polls/detail.html
{% extends "polls/layout.html" %}

{% block content %}
    <div class="content">
        <p class="title">{{ question.question_text }}</p>

        {% if error_message %}<p>{{ error_message }}</p>{% endif %}
    
        <form action="{% url 'polls:vote' question.id %}" method="post">
            {% csrf_token %}
            {% for choice in question.choice_set.all %}
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" required>
                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
            {% endfor %}
            <input type="submit" value="Vote">
        </form>
    </div>
{% endblock content %}

firstsite/polls/templates/polls/index.html
{% extends "polls/layout.html" %}

{% block content %}
    <div class="content">
        <p class="title">Les dernières questions</p>
        {% if latest_question_list %}
            <ul>
            {% for question in latest_question_list %}
                <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
            {% endfor %}
            </ul>
        {% else %}
            <p>No polls are available.</p>
        {% endif %}
    </div>
{% endblock content %}

firstsite/polls/templates/polls/layout.html
{% load static %}
<html>
    <head>
        <title>Django first app</title>
        <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    </head>
    <body>
        <header>
            <div class="logo">
                <p class="logo-title">Django first app</p>
            </div>
            <nav>
                <ul>
                    <li><a href="{% url 'polls:index'%}">Home</a></li>
                    {% if user.is_authenticated %}
                        <li><a href="#">{{ user.get_username }}</a> (<a href="{% url 'poll:logout' %}">Logout</a>)</li>
                    {% else %}
                        <li><a href="{% url 'poll:signin' %}">Login</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>

        {% if messages %}
            <ul class="messages">
            {% for message in messages %}
                <li {%if message.tags %} class="{{message.tags}}-message" {%endif %}>{{ message }}</li>
            {% endfor %}
            </ul>
        {% endif %}    

        <main>
            {% block content %}
            {% endblock %}
        </main>
        <footer>
            <div class="copyrigth">
                &copy; Maxime Chevallier-Pichon 2018
            </div>
            <div class="admin">
                <a href="{% url 'admin:index' %}">Administration</a>
            </div>
        </footer>
    </body>
</html>

firstsite/polls/templates/polls/login.html
{% extends "polls/layout.html" %}

{% block content %}
    <div class="content small">
        <p class="title">Login</p>
        <form action="{% url 'polls:login' %}" method="post">
            {% csrf_token %}
            <fieldset>
                <label for="username">Username :</label>
                <br>
                <input type="text" name="username" id="username" required>
                <br>
                <label for="password">Password :</label>
                <br>
                <input type="password" name="password" id="password" required>
                <br>
                <input type="submit" value="Login">
            </fieldset>
            <fieldset>
                <a href="{% url 'polls:register_page' %}">Register</a>
            </fieldset>
        </form>
    </div>
{% endblock content %}

firstsite/polls/templates/polls/register.html
{% extends "polls/layout.html" %}

{% block content %}
    <div class="content small">
        <p class="title">Register</p>
        <form action="{% url 'polls:register' %}" method="post">
            {% csrf_token %}
            <fieldset>
                <label for="username">Username :</label>
                <br>
                <input type="text" name="username" id="username" required>
                <br>
                <label for="password">Password :</label>
                <br>
                <input type="password" name="password" id="password" required>
                <br>
                <label for="cpassword">Confirm password :</label>
                <br>
                <input type="password" name="cpassword" id="cpassword" required>
                <br>
                <input type="submit" value="Register">
            </fieldset>
            <fieldset>
                <a href="{% url 'polls:login_page' %}">Login</a>
            </fieldset>
        </form>
    </div>
{% endblock content %}

firstsite/polls/templates/polls/results.html
{% extends "polls/layout.html" %}

{% block content %}
    <div class="content">
        <p class="title">Results</p>
            <p>{{ question.question_text }}</p>

            <ul>
            {% for choice in question.choice_set.all %}
                <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
            {% endfor %}
            </ul>
        
            <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
    </div>
{% endblock content %}